CREATE TABLE ESOCIAL_PARAMS (
    ID                   INTEGER NOT NULL,
    TEMPLATES_ROOT       VARCHAR(255) NOT NULL,
    SCHEMAS_ROOT         VARCHAR(255) NOT NULL,
    AMBIENTE             VARCHAR(50) NOT NULL,
    CNPJ_SH              CHAR(14) NOT NULL,
    TOKEN_SH             VARCHAR(255) NOT NULL,
    DIGITAL_CERTIFICATE  VARCHAR(500),
    PIN_A3               VARCHAR(255),
    "VERSION"            VARCHAR(255) NOT NULL,
    CNPJ_TRANSMISSOR     VARCHAR(14),
    CNPJ_EMPREGADOR      VARCHAR(14),
    UPDATED_AT           VARCHAR(255),
    CNPJ_EFR             VARCHAR(14),
    TAM_LOTE             CHAR(5)
);